{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.25.0/atomicfu-0.25.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-androidnativex86-0.25.0.klib",
          "size": 51120,
          "sha512": "2a833a99db46838423a8943de58e29edcc50476ed596ae0e50168e69df0f7b0178d5af8ee7ec38b24f4c8d56e2ebfc1b4e7c10f3f7e9cd86b8014f7e727b7b8f",
          "sha256": "147e71071bf8edf7246afabc647bcc42f23cfe827c321c51a89d613b492a4c86",
          "sha1": "32d79567ad3e8b5efc36991e7c228ab4598340ca",
          "md5": "704eb74e7804d302cc05c19b4632a191"
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-androidnativex86-0.25.0-cinterop-interop.klib",
          "size": 3782,
          "sha512": "33aaf77af005b434c2f46721af87470a129708ff97687b8d95f356f5474391aa91f933be768dfcb91e76ae698d0ef3828f8a0aa37872ac3b63c93d72bb8089ce",
          "sha256": "daa0b5e005015f06f8e379d368a4e8dad39ac778ce1366c672b1b40a2642233f",
          "sha1": "159eb5e266baf8599bedae6cda9e3d3f87c0ad70",
          "md5": "03ebc4350422b85817e5bbd5cac5b743"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "atomicfu-androidnativex86-0.25.0-sources.jar",
          "url": "atomicfu-androidnativex86-0.25.0-sources.jar",
          "size": 12696,
          "sha512": "dfcd37df57802819c7cc884a48977cd711c81294cfb6af959914aa8196cb3fd96ae0a325c9ab5c76bc069b84861ef85308705dcab393216d4344bed33d7fbac1",
          "sha256": "d594f14d386c78a6f24adf321440739510045c5aa41c776ccfbd7b025c09528c",
          "sha1": "6ff8bfdfef7e53415cd4eadfe17f62fd04e3d8ea",
          "md5": "c16ea755af4a030fca521b92cb80e10f"
        }
      ]
    }
  ]
}
