{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.9.0/kotlinx-coroutines-core-1.9.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core.klib",
          "url": "kotlinx-coroutines-core-watchosarm32-1.9.0.klib",
          "size": 889035,
          "sha512": "55aee8763c9dbd91317380e26a831cb62120a90e44f1aa38b1c5ba04df710e16868efd62640fe541a052341fd773e6f29c1da2ad6291bbd6a73c7e2bfed9da9f",
          "sha256": "4c36b81223f785cbad2fd7585fa7b29be201df42255d5bdb93edc7f92a012ef9",
          "sha1": "af7d5f754e4ccb9d316e6b79d7c5a5aa2ad69ac2",
          "md5": "4abd79635c50b99dffc874bae6d3215f"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-watchosarm32-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-core-watchosarm32-1.9.0-sources.jar",
          "size": 315839,
          "sha512": "0c7a21fb4746545595e2dac2894acf3b6f2abb3cd04f800ec6244dff94585a6e8289f9ffed512908545c17a26756b5b008adb8adfab0e963d32617fdd9cfa8f6",
          "sha256": "4bd6a336d7c9887d9be30dabe76e170a208ec3e400873e7261aee1a8f2dae7da",
          "sha1": "a68d3623081cbe7f30e4f9799b8db0831b83672c",
          "md5": "fef705a5b8237391dc4dd4c9b4931970"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-watchosarm32-1.9.0-metadata.jar",
          "url": "kotlinx-coroutines-core-watchosarm32-1.9.0-metadata.jar",
          "size": 3533,
          "sha512": "f00c48a1710cb54a82e1c60cd32a3840a0b8378fdcc591c8d7713b8a374fa240d53fa0c40cccd119603d5a579b694af3f294dd60d555da55358fd9259c84680e",
          "sha256": "75811c7c67cfd2fd80f44bd2ecdb1ec5b6cdb46139e50f1f8a5713c38edf978e",
          "sha1": "adb735ec6208f7bf716bdc2ea2b47c144d3e8af9",
          "md5": "f9a4b9703302a28bfc2eaba70b8d14c6"
        }
      ]
    }
  ]
}
