{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.25.0/atomicfu-0.25.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-tvosarm64-0.25.0.klib",
          "size": 51176,
          "sha512": "11cc75d4c01db06bc3cad782d9ebc15cbde071a6cc0f5369c6cdbfed5a800529b36c94961ed964109fe4bf265f77ec31e268ce5f7a002a8fe7a3e603ddaa80fc",
          "sha256": "0c745a654b5b9e0bc1795b719f025f14db8e110245f4fde89de4f8aa98d0ada0",
          "sha1": "e7e83d3084e5ab3da3a7ebb3428a95fcbcaa23af",
          "md5": "eb7fcd3136e57dccea8af1d5f0d44a4d"
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-tvosarm64-0.25.0-cinterop-interop.klib",
          "size": 3765,
          "sha512": "157076181e6e78556ad0147f66491762f6c8f93b1e8c0ad6997277630748e8481dfc505bdb8c4a6b0b96ea09845bad6f20f30cc627e0a4077e40def8af97ba1a",
          "sha256": "6b65c89b658b023ccb42ae9fd765b489a049555d6a774174625db2babbcc9b0e",
          "sha1": "d1beed7848a85d03cb2d6c9e4f67c12d3af4dde1",
          "md5": "7b07859e5e4c0acbb54aa4dde7f3ab69"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "atomicfu-tvosarm64-0.25.0-sources.jar",
          "url": "atomicfu-tvosarm64-0.25.0-sources.jar",
          "size": 12642,
          "sha512": "700d806d1bae74ef43ed26465e7e325b190b96e593c8460e3c8e947e23430bf611efc50d4f2ecd92c57ecd83786627d581bcf8362b9757d6cc2b4bc18a73a61a",
          "sha256": "7416a0b767b67e97b11a34ea3399b55c40a04300921e9ede73d45fee6ed61584",
          "sha1": "08781f11fd8f4d7b2e37a6816798648d478c5403",
          "md5": "bffb1e99fa46163f9c87ce84950348d7"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-tvosarm64-0.25.0-metadata.jar",
          "url": "atomicfu-tvosarm64-0.25.0-metadata.jar",
          "size": 12648,
          "sha512": "6f7a753f17e74745137cc8d88a021c9314ede41a4b978938633b27be86ca031962ef828ab1aadd4b99181edf9442ade22640c669a9ab5b9428cf61dbb2d915dc",
          "sha256": "8ef5801f0993becf8bc9931ca8d17446f8b20cfd1050596064d12d887b3ddcc8",
          "sha1": "64b25682e88323a7481507073c01fdf12bc32709",
          "md5": "52de1ed0527ce5c69600f259a51f175f"
        }
      ]
    }
  ]
}
