{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test-wasm",
    "version": "1.8.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "wasmApi",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-wasm-1.8.22.klib",
          "url": "kotlin-test-wasm-1.8.22.klib",
          "size": 104006,
          "sha512": "c39781cf971daabc15ac6d2c2c4f1cbe0ffbaa1e56cbeaca0b653941ee29ff1c44a2289f1969c5e485baec827e13fd1a3cd6f3f8614f26630edeabb143198d40",
          "sha256": "b93bbb15579e8ff6caf21ebcc127b0ed0b76cdc258562632d04145184dee2479",
          "sha1": "989ebd79ee8409f325adf7412d57fe5ea0a930a3",
          "md5": "868d809842760924bcd4e6b992f57799"
        }
      ]
    },
    {
      "name": "wasmRuntime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-wasm-1.8.22.klib",
          "url": "kotlin-test-wasm-1.8.22.klib",
          "size": 104006,
          "sha512": "c39781cf971daabc15ac6d2c2c4f1cbe0ffbaa1e56cbeaca0b653941ee29ff1c44a2289f1969c5e485baec827e13fd1a3cd6f3f8614f26630edeabb143198d40",
          "sha256": "b93bbb15579e8ff6caf21ebcc127b0ed0b76cdc258562632d04145184dee2479",
          "sha1": "989ebd79ee8409f325adf7412d57fe5ea0a930a3",
          "md5": "868d809842760924bcd4e6b992f57799"
        }
      ]
    }
  ]
}
