{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.25.0/atomicfu-0.25.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-macosx64-0.25.0.klib",
          "size": 51168,
          "sha512": "80932a6a03410cd63b48ce146f35fea9c3bc6d411e49599e87c91a1735540eaf057d4d08ea730131fefa1999b05658ce9f7ead27344b08eb3211ad3857e0236c",
          "sha256": "2015c0b58a48b52363c437000464832332e72b7e352391d738ac0a789e506f34",
          "sha1": "b5a4a85a69282fe56c06a04227abc2ef27cb558f",
          "md5": "e9894097571d375d92e57d5294a269a0"
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-macosx64-0.25.0-cinterop-interop.klib",
          "size": 3802,
          "sha512": "27ee557eacfb78f5ea1ca92f802d5460d4a19fdddfc620d4c542b86b75daa2dc8e6f48c5f81036a16cac5ccda0b079dbd7ac0a6031be948f8ee25f4df53340ad",
          "sha256": "3040b74f0cd5b7353340bd7e8571599223edf0e2862e397c57641c163b6895ce",
          "sha1": "58c92a959d149afb3ea93e165f24d6deceaaef44",
          "md5": "2541482926e7b4070a5a5cc1f2887009"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "atomicfu-macosx64-0.25.0-sources.jar",
          "url": "atomicfu-macosx64-0.25.0-sources.jar",
          "size": 12642,
          "sha512": "700d806d1bae74ef43ed26465e7e325b190b96e593c8460e3c8e947e23430bf611efc50d4f2ecd92c57ecd83786627d581bcf8362b9757d6cc2b4bc18a73a61a",
          "sha256": "7416a0b767b67e97b11a34ea3399b55c40a04300921e9ede73d45fee6ed61584",
          "sha1": "08781f11fd8f4d7b2e37a6816798648d478c5403",
          "md5": "bffb1e99fa46163f9c87ce84950348d7"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-macosx64-0.25.0-metadata.jar",
          "url": "atomicfu-macosx64-0.25.0-metadata.jar",
          "size": 12648,
          "sha512": "6e89e0598f61f903c25a33b4cd8bca736d5b425a81cb32e898785d706b4901d93eff610f7f329316f715bc319dd8d8db2307abe4ae1a9ffdd752c4262c446739",
          "sha256": "b7eb3cc96149ceff3c394737768f877141c00c2c812237cf6dad13b8e1f7ace1",
          "sha1": "465327cf538752a708c4b8645ad312eca472f04e",
          "md5": "70c3f73eda98cb2c01e9f2c66514c601"
        }
      ]
    }
  ]
}
