{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing-wire/2.0.0-alpha08/tracing-wire-2.0.0-alpha08.module",
    "group": "androidx.tracing",
    "module": "tracing-wire",
    "version": "2.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "15390118"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha08"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha08"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha08"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire.aar",
          "url": "tracing-wire-android-2.0.0-alpha08.aar",
          "size": 187187,
          "sha512": "987500a9246920829dfb3560ca38dd3f49f4149f17ae0ab365acf16f32778f3d34ae4e39598c23cd1b1bd9d8d70abe4afd26462e44f6b5144e5bb57685a98429",
          "sha256": "603f67eaae954df8002d69b90100470c5375cb65ce851e1700473f0468e1820a",
          "sha1": "0ec5dcabf266d28ce59b70162ed8ce541643a0fb",
          "md5": "21147ede305c2dbabed95475274adaf1"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha08"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha08"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha08"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire.aar",
          "url": "tracing-wire-android-2.0.0-alpha08.aar",
          "size": 187187,
          "sha512": "987500a9246920829dfb3560ca38dd3f49f4149f17ae0ab365acf16f32778f3d34ae4e39598c23cd1b1bd9d8d70abe4afd26462e44f6b5144e5bb57685a98429",
          "sha256": "603f67eaae954df8002d69b90100470c5375cb65ce851e1700473f0468e1820a",
          "sha1": "0ec5dcabf266d28ce59b70162ed8ce541643a0fb",
          "md5": "21147ede305c2dbabed95475274adaf1"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha08"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha08"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-android-2.0.0-alpha08-sources.jar",
          "url": "tracing-wire-android-2.0.0-alpha08-sources.jar",
          "size": 63408,
          "sha512": "c7f3845680df66da349bef8d5ca5953734b52dd17091a22877da0a2140f7cb72df4f8c79327a6ba674d95262151233516bc3f15ec2d4655b5cf1562c5d02ec58",
          "sha256": "dca1ec771de62da5b2bfd98b726fa81064557ea5140e2a2d1241f1832baf5b45",
          "sha1": "4ccacd87f55aa903ce85b4c6842926d2bbd29c69",
          "md5": "893de7631053cab634a1a71808ffda54"
        }
      ]
    }
  ]
}