{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.9.0/kotlinx-coroutines-core-1.9.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core.klib",
          "url": "kotlinx-coroutines-core-linuxarm64-1.9.0.klib",
          "size": 884396,
          "sha512": "a1075d43a4c677eaa02ac738d7bc31be84582cfeecac881023a7496702ae8a696ac462c7a22161ea09234d6b5abd93c42df69218f1684bc64420e091d8a4fb7a",
          "sha256": "ac9d43390a55e158c62af847a3b1ed866b36ed839db781e2a2268646bb53c399",
          "sha1": "84808e92a7e02b6ed2647b0876a6e5f251272a9c",
          "md5": "ad2d3d308d467bbc8cecbfa367c06e0c"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-linuxarm64-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-core-linuxarm64-1.9.0-sources.jar",
          "size": 315262,
          "sha512": "3045cf76e39b76b248d79e6321d62cc53a332ee571bd9c10cbdb58d618908d610c1f5fc2198d2b218b710022499c850d9c5be630e84848629bb0f65b658e2a36",
          "sha256": "66cc38af5996840733083e5b7a5547eaed16ad307040e02aae506eab07ffa97a",
          "sha1": "f1c03bb38919579ae99adfada139e7d59051818b",
          "md5": "beb84c66c1e751ec72a12794dd80ad32"
        }
      ]
    }
  ]
}
