{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing-wire/2.0.3/tracing-wire-2.0.3.module",
    "group": "androidx.tracing",
    "module": "tracing-wire",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "16342595"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire.aar",
          "url": "tracing-wire-android-2.0.3.aar",
          "size": 192569,
          "sha512": "610dd777432a6949c43333ac80731476d5514b6789820c61f1a9d623f25c6af1225430c76497b2d298ce2461f4283bbf4aae682c89b54470d050749038e6dca7",
          "sha256": "e0f5ba2eca6db4388b47f6fca024575e2ee67a5cdee7403d8b437b80c3bdcaf3",
          "sha1": "c053e014a204243234f6a289b7f9ebebe51dfb40",
          "md5": "d07cbd7d7aa264a8f442f9968f97cfde"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire.aar",
          "url": "tracing-wire-android-2.0.3.aar",
          "size": 192569,
          "sha512": "610dd777432a6949c43333ac80731476d5514b6789820c61f1a9d623f25c6af1225430c76497b2d298ce2461f4283bbf4aae682c89b54470d050749038e6dca7",
          "sha256": "e0f5ba2eca6db4388b47f6fca024575e2ee67a5cdee7403d8b437b80c3bdcaf3",
          "sha1": "c053e014a204243234f6a289b7f9ebebe51dfb40",
          "md5": "d07cbd7d7aa264a8f442f9968f97cfde"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-android-2.0.3-sources.jar",
          "url": "tracing-wire-android-2.0.3-sources.jar",
          "size": 65792,
          "sha512": "60a5f5083e9577b9074e78e4f647cf0d1b4b4f114cbfccd1d234a28ec71ac52aded677e37856786d0a9dd43da9c59cf55ec21fca89b23f50c0caaf6edf6741a4",
          "sha256": "b4750670912446177cf235dd09f885228f798fe6f6b6213cac255106162d20ea",
          "sha1": "6a886ce522893d41fa2706689d751ff0ee1fbb6c",
          "md5": "7ef4425a016087248af1e3fbdef61116"
        }
      ]
    }
  ]
}