{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing/2.0.0-alpha06/tracing-2.0.0-alpha06.module",
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "2.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-1",
      "buildId:": "15216785"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing.aar",
          "url": "tracing-android-2.0.0-alpha06.aar",
          "size": 137405,
          "sha512": "f3ec5336c098b1fdf84ba15a382ad66bc0d497c002bd22d536427603849dbcbe30c6a2ce08162a31303df2b5c5e02de2c8373a204e49f3571e33dcf384e12e5d",
          "sha256": "55986b77f8cef9658ebfe45e31a05df3239490246b29b6ea5f893fd91fd6552b",
          "sha1": "3f63d4fec968c508894741831367a4b8e9092315",
          "md5": "19ae4ee780bce951dff6803c32ac1b2b"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing.aar",
          "url": "tracing-android-2.0.0-alpha06.aar",
          "size": 137405,
          "sha512": "f3ec5336c098b1fdf84ba15a382ad66bc0d497c002bd22d536427603849dbcbe30c6a2ce08162a31303df2b5c5e02de2c8373a204e49f3571e33dcf384e12e5d",
          "sha256": "55986b77f8cef9658ebfe45e31a05df3239490246b29b6ea5f893fd91fd6552b",
          "sha1": "3f63d4fec968c508894741831367a4b8e9092315",
          "md5": "19ae4ee780bce951dff6803c32ac1b2b"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-android-2.0.0-alpha06-sources.jar",
          "url": "tracing-android-2.0.0-alpha06-sources.jar",
          "size": 69299,
          "sha512": "5612faff8df878ad31e71d4124b0c39ff2afd1794a492779098c24a8d5fb95b08e34542cb79b346bd0078d062b771f7a4d4ef2d2e38d45b0f90cd28b18003d34",
          "sha256": "48b7172aac991988f9602518aaf4858964723fd8895c3abc85831e0e195abe57",
          "sha1": "bee7ae3674f26fd049cae1a833ca905fd804f2b3",
          "md5": "f5595dc49116f448f4118caf5ea3ec21"
        }
      ]
    }
  ]
}