{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.9.0/kotlinx-coroutines-core-1.9.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core.klib",
          "url": "kotlinx-coroutines-core-mingwx64-1.9.0.klib",
          "size": 884379,
          "sha512": "6642e848aebd38533d8e22a68d61b4111d732f757580d6d875703d8cb4b2eedb06713cb626047bd5753f2c9b870c9dc427fe5fff767cf4c48e20aef142676f22",
          "sha256": "2c94fc9037f23c8858f8b1be2ff92fac54551426c605f1dd3b38fee37a3a7259",
          "sha1": "1ff5b79203243ec0aa8b5fff54428993fedf50e9",
          "md5": "55f894b41075479d07fe073c506ecfbe"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-mingwx64-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-core-mingwx64-1.9.0-sources.jar",
          "size": 315262,
          "sha512": "3045cf76e39b76b248d79e6321d62cc53a332ee571bd9c10cbdb58d618908d610c1f5fc2198d2b218b710022499c850d9c5be630e84848629bb0f65b658e2a36",
          "sha256": "66cc38af5996840733083e5b7a5547eaed16ad307040e02aae506eab07ffa97a",
          "sha1": "f1c03bb38919579ae99adfada139e7d59051818b",
          "md5": "beb84c66c1e751ec72a12794dd80ad32"
        }
      ]
    }
  ]
}
