{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.25.0/atomicfu-0.25.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-watchossimulatorarm64-0.25.0.klib",
          "size": 51289,
          "sha512": "0e47370cedb22da6857045b39bf7ea5c8db70de313ce4c986840dd991526a1f3a29e39248cba47c6ad413189ac045c107c765d379dbf834885010963d72caf47",
          "sha256": "2124047b6fb3e2356b37d2f10c6d58ffe359a957147f684fe207cb48427c1f07",
          "sha1": "c7d28dd2aee57e4c73145210915efa07c89d37b0",
          "md5": "02cba778c8d01e73b896d08758e98886"
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-watchossimulatorarm64-0.25.0-cinterop-interop.klib",
          "size": 3936,
          "sha512": "1ad56e678c8687337d5f2106292e85d4ca833d3c097fb3f99fe11f7cb4640679c5a661c5a046244e9a7f7c68c330241d722808edadbd74ac214d501225e5b74c",
          "sha256": "e4827175caee7ef3c980b66c363e2cbf56e14ba25b02a1957a6241f61f489568",
          "sha1": "f05535dd9035e229973797340ecb32a213940b7f",
          "md5": "0c811aea7f378d1e88b62f6fe5d71e42"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "atomicfu-watchossimulatorarm64-0.25.0-sources.jar",
          "url": "atomicfu-watchossimulatorarm64-0.25.0-sources.jar",
          "size": 12642,
          "sha512": "700d806d1bae74ef43ed26465e7e325b190b96e593c8460e3c8e947e23430bf611efc50d4f2ecd92c57ecd83786627d581bcf8362b9757d6cc2b4bc18a73a61a",
          "sha256": "7416a0b767b67e97b11a34ea3399b55c40a04300921e9ede73d45fee6ed61584",
          "sha1": "08781f11fd8f4d7b2e37a6816798648d478c5403",
          "md5": "bffb1e99fa46163f9c87ce84950348d7"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-watchossimulatorarm64-0.25.0-metadata.jar",
          "url": "atomicfu-watchossimulatorarm64-0.25.0-metadata.jar",
          "size": 12648,
          "sha512": "a0fc389ddf1635679f0764589badebb053e8cc62621e5f42527f2df90963f9505cbc1b0ba04469a7aa48b5f9c9af9e8cc7c28871e149ad642c9dabb5dabb5819",
          "sha256": "ce2dbcc6e508aef011c71d438691d8b2bf7353edf1bf5a029c4451b36f8a470b",
          "sha1": "7e847a6de71266329c06f9e2fb042b7143c5efea",
          "md5": "d02dd49bcc193aaefa401fa73ae323a6"
        }
      ]
    }
  ]
}
