{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.9.0/kotlinx-coroutines-core-1.9.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core.klib",
          "url": "kotlinx-coroutines-core-tvosx64-1.9.0.klib",
          "size": 888989,
          "sha512": "72569d42ad90abdcebfa0b3bab3ea741c8201eee2dbdb56670ffa32071aedd7f4b4174b7801d6bd6a7638193dc83b10b60994eb190aa49bf5e3f616f7fcab534",
          "sha256": "c81dc6fb1386e09f93df8d75d22c3f16a1348b486d0625767e6bc102244668d9",
          "sha1": "344e2a78598a0e6e4bf6e9ed9fb2f46e4b9f8e88",
          "md5": "aadcea3227f669acf7ac9b8ff3663c14"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvosx64-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-core-tvosx64-1.9.0-sources.jar",
          "size": 315839,
          "sha512": "0c7a21fb4746545595e2dac2894acf3b6f2abb3cd04f800ec6244dff94585a6e8289f9ffed512908545c17a26756b5b008adb8adfab0e963d32617fdd9cfa8f6",
          "sha256": "4bd6a336d7c9887d9be30dabe76e170a208ec3e400873e7261aee1a8f2dae7da",
          "sha1": "a68d3623081cbe7f30e4f9799b8db0831b83672c",
          "md5": "fef705a5b8237391dc4dd4c9b4931970"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-tvosx64-1.9.0-metadata.jar",
          "url": "kotlinx-coroutines-core-tvosx64-1.9.0-metadata.jar",
          "size": 3533,
          "sha512": "6e2721d1be49d0f4ab111979ae9db83a3506eee7aafdb7edf49078cb60bcc8eb164ea005360f4948025a6d21296222fec4f06d4b5220c25b44fc3b26e2663d71",
          "sha256": "4e2f5afb33c27930d535822ff84a775555e30034936d4714ea7fdba5b62d92c5",
          "sha1": "49b07ef0688e15f57cd5bda714628cc0db9fb66d",
          "md5": "eaacc6a48c340b5eec3a6c2d1643c2d8"
        }
      ]
    }
  ]
}
