{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing/2.0.3/tracing-2.0.3.module",
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "16342595"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-desktop-2.0.3.jar",
          "url": "tracing-desktop-2.0.3.jar",
          "size": 147336,
          "sha512": "a0e0de06c7c7706cd44c7d62ee2f2ff8942f7d5f9bad2f1e56e8af1fe36f0b8e916c51dd1685c61e527b15ed3bb6002659a02edb581b3cd9f61143d7c8003932",
          "sha256": "06a950da1802cb02c1ff0619c100f291bc040a7c4c02abb138279aefad15fb1d",
          "sha1": "ed55e15415c867ed26ee67fa4e0d9ee6077535d6",
          "md5": "3b25e7108df269c9b2ccc7d5f61b629e"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-desktop-2.0.3.jar",
          "url": "tracing-desktop-2.0.3.jar",
          "size": 147336,
          "sha512": "a0e0de06c7c7706cd44c7d62ee2f2ff8942f7d5f9bad2f1e56e8af1fe36f0b8e916c51dd1685c61e527b15ed3bb6002659a02edb581b3cd9f61143d7c8003932",
          "sha256": "06a950da1802cb02c1ff0619c100f291bc040a7c4c02abb138279aefad15fb1d",
          "sha1": "ed55e15415c867ed26ee67fa4e0d9ee6077535d6",
          "md5": "3b25e7108df269c9b2ccc7d5f61b629e"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.3"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-desktop-2.0.3-sources.jar",
          "url": "tracing-desktop-2.0.3-sources.jar",
          "size": 68534,
          "sha512": "e4c1354e3f8294db977a922bd69f8f210cad06ccd00c534e9e847178af6ebe513f731877878c420cfa643e61063abd6b3242729fd4978fb7f927d17c81865152",
          "sha256": "c774525ec99897c75edacb84dc59f8442726b81476ddd1660a1e7890eec25247",
          "sha1": "75f8b731c8b7023fa00d965d86fd2738f1485532",
          "md5": "834353693b3c8e13325dbfc091dc1e0e"
        }
      ]
    }
  ]
}