{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "16530026"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-metadata-2.0.4.jar",
          "url": "tracing-2.0.4.jar",
          "size": 4876,
          "sha512": "ec6465a6ee16169c07fa6c4813f03dbe6e75f767cb99caa6cccafb27187f3aee9718050661e22fbe0dea3362b68a15fbd3b3bfabde9bfc0d91322895fd8ea68d",
          "sha256": "aac3444bdcff86f2e0e46cbe3a857393c248cb946eeede5bd67ab823647c7db2",
          "sha1": "9b0b872cbc2a2a5c1993c408695db57f7241ce29",
          "md5": "c07a6528b9671f079fef7685da76eada"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-kotlin-2.0.4-sources.jar",
          "url": "tracing-2.0.4-sources.jar",
          "size": 62535,
          "sha512": "df61ae4f3ded16f1ae7db5eca992e89f6dd8cd80ea9160036d9a5e049e679e24df2d0da1f1dd70ffd866445d8df84478d51f598347593f5c2696de7f533a88ba",
          "sha256": "13c6eac9803e96c2f7ccc3702885cffb6df9703d1dbdec24afcbc20ed24b2b2e",
          "sha1": "9be61727934e19b01808a0a57dbf9b5f8aa0e1c8",
          "md5": "ad58d5737bcaec5219dcd59689b6c23e"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-2.0.4-multiplatform-sources.jar",
          "url": "tracing-2.0.4-multiplatform-sources.jar",
          "size": 79848,
          "sha512": "bc5b16235528692b20dc26241a1a625c5b737bf3bb264e16f46290be5f8783a7ca1e1b1d67e76c8bb4c6d425ccfed574b3e142bb1f872ee15b9c3d7625e83704",
          "sha256": "a022118cfb7fc55f2cd4e57fb8f706c76b6aa4110626266de25ea8cf21c56bb1",
          "sha1": "ff20ae13f2a9d69f79b429ddd4f78a6c89224ee1",
          "md5": "a8e3bd5a0bd54798a3e485483de47e07"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "tracing-2.0.4-versionMetadata.json",
          "size": 13815,
          "sha512": "b1e4ba112db6a312425a78040216141505b50911c3b3ccf433d70fcb2125a7c501d0ca4e0a35451ab00cee5ea9c94962d271b69320914a20d173bfeaca4d64d3",
          "sha256": "cedf524d693b033201061c84b1a5ea2181366682ea0f49f7b871c30bd0ca0c88",
          "sha1": "dd936230807adb036a01d06706e7bf9f7ff068cd",
          "md5": "f224bf98c474c1be6a6932cbd9d4006c"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-android/2.0.4/tracing-android-2.0.4.module",
        "group": "androidx.tracing",
        "module": "tracing-android",
        "version": "2.0.4"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-android/2.0.4/tracing-android-2.0.4.module",
        "group": "androidx.tracing",
        "module": "tracing-android",
        "version": "2.0.4"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-android/2.0.4/tracing-android-2.0.4.module",
        "group": "androidx.tracing",
        "module": "tracing-android",
        "version": "2.0.4"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-desktop/2.0.4/tracing-desktop-2.0.4.module",
        "group": "androidx.tracing",
        "module": "tracing-desktop",
        "version": "2.0.4"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-desktop/2.0.4/tracing-desktop-2.0.4.module",
        "group": "androidx.tracing",
        "module": "tracing-desktop",
        "version": "2.0.4"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-desktop/2.0.4/tracing-desktop-2.0.4.module",
        "group": "androidx.tracing",
        "module": "tracing-desktop",
        "version": "2.0.4"
      }
    }
  ]
}