{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.25.0/atomicfu-0.25.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "atomicfu-wasm-js-0.25.0.klib",
          "url": "atomicfu-wasm-js-0.25.0.klib",
          "size": 36342,
          "sha512": "7bbd55dde379d08f0b6a50850f1fc4fb91e5f402c9b534a82dc0ad73cc5a0c404a5625bb232665fe07badcc660a87b7dd3bfd313b943b5c092cf15dff1af5157",
          "sha256": "3fd456001e2143d682aafdb6ad5dd7db4bac8f9ed5911f542ef76de2ad2452cf",
          "sha1": "5eaf47e6281bf2abafe0fd02404628407e07d2a7",
          "md5": "78bb057dfda2524efe941b220b9c57c4"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-wasm-js-0.25.0.klib",
          "url": "atomicfu-wasm-js-0.25.0.klib",
          "size": 36342,
          "sha512": "7bbd55dde379d08f0b6a50850f1fc4fb91e5f402c9b534a82dc0ad73cc5a0c404a5625bb232665fe07badcc660a87b7dd3bfd313b943b5c092cf15dff1af5157",
          "sha256": "3fd456001e2143d682aafdb6ad5dd7db4bac8f9ed5911f542ef76de2ad2452cf",
          "sha1": "5eaf47e6281bf2abafe0fd02404628407e07d2a7",
          "md5": "78bb057dfda2524efe941b220b9c57c4"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "atomicfu-wasm-js-0.25.0-sources.jar",
          "url": "atomicfu-wasm-js-0.25.0-sources.jar",
          "size": 9493,
          "sha512": "04c22ce24a6d14552bcf48b2fa4fec22d4b503681bf4ca2ef2187db055ffbc867fbc7d6189ee71aacc088f3cfb2fa5a21f23f84c5ac3cc45922914cc73be5f27",
          "sha256": "712904e0b487e12e43bfcf36e7d052d0c62cfb993a8ddf204482db09dd4f2f96",
          "sha1": "416b32f0c953182c070a7baf7e2501b82ed170d9",
          "md5": "64e186fb63ac63815aa36d293344679e"
        }
      ]
    }
  ]
}
