{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing-wire/2.0.4/tracing-wire-2.0.4.module",
    "group": "androidx.tracing",
    "module": "tracing-wire",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "16530026"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire.aar",
          "url": "tracing-wire-android-2.0.4.aar",
          "size": 192569,
          "sha512": "88e9553b4d5251b3c637d968ff3ef9b45baa6b876911b0b6989db77a3fa67274abaf77e00d4617fc8fac22c7689367bd191d655591df7d1390264490bd223c03",
          "sha256": "457b96d6dbaad0bea2855b6c848ad512b0344804aa2cb1fb998faffb4cc53b71",
          "sha1": "bdc9fde26b38aedff8601c79889adf3db8a645a8",
          "md5": "4d185f865fceab33e2d873969e4b9400"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire.aar",
          "url": "tracing-wire-android-2.0.4.aar",
          "size": 192569,
          "sha512": "88e9553b4d5251b3c637d968ff3ef9b45baa6b876911b0b6989db77a3fa67274abaf77e00d4617fc8fac22c7689367bd191d655591df7d1390264490bd223c03",
          "sha256": "457b96d6dbaad0bea2855b6c848ad512b0344804aa2cb1fb998faffb4cc53b71",
          "sha1": "bdc9fde26b38aedff8601c79889adf3db8a645a8",
          "md5": "4d185f865fceab33e2d873969e4b9400"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.4"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-android-2.0.4-sources.jar",
          "url": "tracing-wire-android-2.0.4-sources.jar",
          "size": 65792,
          "sha512": "60a5f5083e9577b9074e78e4f647cf0d1b4b4f114cbfccd1d234a28ec71ac52aded677e37856786d0a9dd43da9c59cf55ec21fca89b23f50c0caaf6edf6741a4",
          "sha256": "b4750670912446177cf235dd09f885228f798fe6f6b6213cac255106162d20ea",
          "sha1": "6a886ce522893d41fa2706689d751ff0ee1fbb6c",
          "md5": "7ef4425a016087248af1e3fbdef61116"
        }
      ]
    }
  ]
}