{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "2.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-1",
      "buildId:": "15216785"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-metadata-2.0.0-alpha06.jar",
          "url": "tracing-2.0.0-alpha06.jar",
          "size": 4876,
          "sha512": "ec6465a6ee16169c07fa6c4813f03dbe6e75f767cb99caa6cccafb27187f3aee9718050661e22fbe0dea3362b68a15fbd3b3bfabde9bfc0d91322895fd8ea68d",
          "sha256": "aac3444bdcff86f2e0e46cbe3a857393c248cb946eeede5bd67ab823647c7db2",
          "sha1": "9b0b872cbc2a2a5c1993c408695db57f7241ce29",
          "md5": "c07a6528b9671f079fef7685da76eada"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-kotlin-2.0.0-alpha06-sources.jar",
          "url": "tracing-2.0.0-alpha06-sources.jar",
          "size": 59267,
          "sha512": "4c75e72c8d32c6798381d56310695a359fb8b209b7dd56f7aca455329fa097e2c39ec51fd676ddb846cd43f5dfd9ffe6b9266d4c1fbcee907541b1973c345b54",
          "sha256": "bd726bbce0788da0bb6374daf11bac668d08bcf7f460f80354fe3ae8b9c00b04",
          "sha1": "ffb6e351ea493fc7ac5a02c84bce2036a3d2b4b9",
          "md5": "c7608571fd98ac101a2dc5b4020e735b"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-2.0.0-alpha06-multiplatform-sources.jar",
          "url": "tracing-2.0.0-alpha06-multiplatform-sources.jar",
          "size": 74739,
          "sha512": "d2de81916b1ac678844bce8172cf9059002801c272cff819dbcc53cf2efc31421b40401915b85720c23cc288209269f55510267abacbd0e25232dc6ea8f5c5cf",
          "sha256": "59ff96c89d17f85e68ebcc2d8a57bee72e990e76ae078eee6030d560a76935e1",
          "sha1": "7e674e679abfaa505907a35e3009ca625eaedb5c",
          "md5": "89189e88b56248c764001cac6aa8a8f3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "tracing-2.0.0-alpha06-versionMetadata.json",
          "size": 13976,
          "sha512": "bd56133779d2d194810293f2ae9ce2753868d6fcea8ed15b524b6b3762ce240dfc50c03b0e6e7fc9809df6bd5e410607039095866554d81c19a3e40e58472967",
          "sha256": "75a6157ae3e92a877094e89e47174082c18feb515c78da9515336317c1eb079c",
          "sha1": "bc55ed982d2e36bff1db91a531eb7e48c463e6c0",
          "md5": "2580018b15a5389b7c6ee5f65660ec6f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-android/2.0.0-alpha06/tracing-android-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-android",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-android/2.0.0-alpha06/tracing-android-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-android",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-android/2.0.0-alpha06/tracing-android-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-android",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-desktop/2.0.0-alpha06/tracing-desktop-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-desktop",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-desktop/2.0.0-alpha06/tracing-desktop-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-desktop",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-desktop/2.0.0-alpha06/tracing-desktop-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-desktop",
        "version": "2.0.0-alpha06"
      }
    }
  ]
}