{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.9.0/kotlinx-coroutines-core-1.9.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core.klib",
          "url": "kotlinx-coroutines-core-androidnativearm32-1.9.0.klib",
          "size": 884411,
          "sha512": "22b3c608a82eb1182e78237a7102651ec8d414a16cb9243021b74aa5460ab58d409214f30a07c25fce28b623832db020517c0e13f08e719a8233b395e358ea9c",
          "sha256": "ec148ae4e68aa57d6ae660a7dec55545a74cd9524394dd9999e60b4099bcf769",
          "sha1": "9f3bb309adfd2d9f59b53c22ca2cff68550c9879",
          "md5": "84475f11477c7d1dccf4c272e482b80a"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-androidnativearm32-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-core-androidnativearm32-1.9.0-sources.jar",
          "size": 315262,
          "sha512": "3045cf76e39b76b248d79e6321d62cc53a332ee571bd9c10cbdb58d618908d610c1f5fc2198d2b218b710022499c850d9c5be630e84848629bb0f65b658e2a36",
          "sha256": "66cc38af5996840733083e5b7a5547eaed16ad307040e02aae506eab07ffa97a",
          "sha1": "f1c03bb38919579ae99adfada139e7d59051818b",
          "md5": "beb84c66c1e751ec72a12794dd80ad32"
        }
      ]
    }
  ]
}
