{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-wire",
    "version": "2.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-1",
      "buildId:": "15216785"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha06"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-metadata-2.0.0-alpha06.jar",
          "url": "tracing-wire-2.0.0-alpha06.jar",
          "size": 4922,
          "sha512": "2b34189dff58728cfe2385a8244c38dfddd8181108858642102818834ac701e75a3257b0a317f2343e774b6f767c091b29d7c0b221782ca6f3fa8c4ce9bbae77",
          "sha256": "b752c39a01622fcab05b1e24727c712a4b071cec0f22a41ff4ead44d9cf8ab27",
          "sha1": "6a4cd8862c7d4091ddd1890953c6f42dfdea1901",
          "md5": "e3d28493f3a4a103487fabd4facc6641"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-kotlin-2.0.0-alpha06-sources.jar",
          "url": "tracing-wire-2.0.0-alpha06-sources.jar",
          "size": 51670,
          "sha512": "594a575078e71863d9cccf324922c8e57710acf6c87ed14d3ac66fb05c4bf2d0f3cf86a8e93bdbeaa3de6d68170957397a4f4f5366573ccb6722bb1b1c9f9fbb",
          "sha256": "652462f858b8929edd9d1cbf88108840e1f98899f947c1b0772d45fb7908f42a",
          "sha1": "b14ceb1a731f9ad8d7a63bea15ec84552b71dbee",
          "md5": "ef962368b7fd1df65a140e175f41f868"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-2.0.0-alpha06-multiplatform-sources.jar",
          "url": "tracing-wire-2.0.0-alpha06-multiplatform-sources.jar",
          "size": 60450,
          "sha512": "38f396ce3a3317421c7e2c4e265ef861654e4c4ef588504f0b8dc251d4fd30482f3cfcfe3258040d802f12b5baa5bd4d578ed54e97769691a6e806af4a75b7ef",
          "sha256": "c5ff8d3fc5df65b71aa2455e65aca39dbc31615cfc3eb247bff60e7996395ed1",
          "sha1": "aabf5ac08b843d576a3ddaef1bcd880e4a3c9292",
          "md5": "cef4a33e9b2b2590659432994af2bdb7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-alpha06"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "tracing-wire-2.0.0-alpha06-versionMetadata.json",
          "size": 3154,
          "sha512": "02581a987fa0010e8aebe69d552f4e475a833e82081c7d039c160741d557b9bc807623480d35303539ecbf81f325d1c9092177a83249587eb0f85365220bb22e",
          "sha256": "6c41d1a4f2248579ee341c609ac65dd3aca8f8a1539358d668cd90620a59bff5",
          "sha1": "3f02c4cba784ccc0adbf51f49c356a6033aa4cf8",
          "md5": "6f15e4cfba6610dc1c37cdc8d2a11767"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-wire-android/2.0.0-alpha06/tracing-wire-android-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-wire-android",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-wire-android/2.0.0-alpha06/tracing-wire-android-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-wire-android",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../tracing-wire-android/2.0.0-alpha06/tracing-wire-android-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-wire-android",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-wire-desktop/2.0.0-alpha06/tracing-wire-desktop-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-wire-desktop",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-wire-desktop/2.0.0-alpha06/tracing-wire-desktop-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-wire-desktop",
        "version": "2.0.0-alpha06"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tracing-wire-desktop/2.0.0-alpha06/tracing-wire-desktop-2.0.0-alpha06.module",
        "group": "androidx.tracing",
        "module": "tracing-wire-desktop",
        "version": "2.0.0-alpha06"
      }
    }
  ]
}